---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.13.8

inputs:
  - name: dp-frontend-geography-controller
    path: dp-frontend-geography-controller

outputs:
  - name: build

run:
  path: dp-frontend-geography-controller/ci/scripts/build.sh
